### PR TITLE
te-Croatia

### PR DESCRIPTION
**Pull request by dahoum**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Is your app/project/product currently shipping and/or have the source code available?
* [ ] If an app, does your homepage include links to download the Android and/or iOS apps?
* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by dahoum** [comment]
LGTM except that I could not find a website for the apps, but they are available both in the Google and Apple app stores, which point back to the web site of the ministry of health, on which there is no mention of the apps.

**Comment by jennydove** [comment]
App website: https://www.koronavirus.hr/stop-covid-19-723/723

Just had to follow a few links from the ministry's homepage. I fixed it in the PR.

**Comment by jennydove** [comment]
Also in this case since the GitHub org is dedicated only to this codebase, you don't need both `project_org` and `repo_url`. We can have just `project_org` in there and it should pull everything. I've updated that as well, waiting for a new build from netlify for one final check before I merge.

**Comment by jennydove** [comment]
Whoops. my bad. I'll get that fixed.

**Pull request merged**
