### PR TITLE
Changed Herald project state. Updates NPM deps for security audit.

### PR DESCRIPTION
**Pull request by adamfowleruk**
Signed-off-by: Adam Fowler <adamfowleruk@gmail.com>

### CODE REVIEW

**Comment by jennydove** [comment]
@adamfowleruk I'm not sure what the changes are that you made to the package and package-lock. Can we chat tomorrow and walk through these before I merge?

**Comment by jennydove** [comment]
checking in again @adamfowleruk - can you help me understand what's happening here?

**Comment by adamfowleruk** [comment]
This was a change to make the Herald project a foundation project after it was accepted as L2 in LFPH. That has since been applied. The other change was a security dependabot change to ensure it's using the latest code with security patches in building the landscape. You may as well close this PR. I'll issue a new one soon that updates all URLs once the website is moved.

**Comment by jennydove** [comment]
thanks for the info!

**Pull request closed without merging**
