### PR TITLE
Add 'Corona Contact Tracing Germany'

### PR DESCRIPTION
**Pull request by alohapersona**
This adds the 'Corona Contact Tracing Germany' app, a reproducible, fully free-software fork of German [Corona-Warn-App](https://www.coronawarn.app/). Check <https://fsfe.org/news/2020/news-20201208-01.en.html>.

Note:
- Crunchbase does not apply, as it's a community project.
- `repo_url` can't be provided as repository is not hosted on GitHub.

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Is the app/project/product currently shipping and/or have the source code available?
* [x] If an app, does your homepage include links to download the Android and/or iOS apps?
* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by dahoum** [comment]
Do you need help?

**Comment by alohapersona** [comment]
@dahoum
I guess CCTG can't be listed in lfph-landscape given that a crunchbase entry seems to be a hard requirement but CCTG is not developed by a company and thus can't provide such. Also apparently you have to host on GitHub to be considered open-source? CCTG hosts on Codeberg, a non-profit alternative to GitHub.

I was also considering to add an entry for @microg which provides an open-source alternative implementation of GAEN for Android. But it's also not developed by a company, so no crunchbase.

I guess crunchbase was a good fit for CNCF which is mostly used by commercial entities. But developing GAEN apps can also be a community effort and does not require a backing company or organization (not even a PHA)

**Comment by alohapersona** [comment]
I just found that according to https://github.com/cncf/landscapeapp/blob/master/README.md#crunchbase-requirement:

> We require all landscape entries to include a Crunchbase url. [...] For open source, non-affiliated projects, we will just create a nonprofit organization representing the project (if one doesn't already exist), and set the location to the lead developer.

So I'll leave this PR as is, so you can do your thing and add create an entry in crunchbase to represent the CCTG developers.

**Comment by dahoum** [comment]
Hey :) The Crunchbase is the lesser problem :) The bigger problem is that there is only one GAEN app per country, so the purpose of the fork is not v clear. Are you available for a short call to clarify the situation? You can email me at t.e.shaw@lfph.io and we can agree when and how. Thank you!

**Comment by alohapersona** [comment]
@dahoum
I'm not a developer of the CCTG app (just a user), but thought it would be useful to add here.

The purpose of the fork is to have a fully free software version of the app, not requiring any proprietary code from Google. It can be installed [from F-Droid](https://f-droid.org/packages/de.corona.tracing/) (the FOSS-only alternative to Play Store) and runs perfectly fine already, even beside the official CWA app on the same device and in Germany. The restriction one app per country afaik only applies to Google Play Store and Apple App Store, not alternative app sources.

I'll ping @mar-v-in, he's developer of microG (the alternative EN implementation used by CCTG) and involved with CCTG and can probably answer any questions.

**Comment by mar-v-in** [comment]
Not sure how I can help here.

The "normal" Google implementation of GAEN requires users/manufacturers to install proprietary components to their operating system (which could have been free software without) and requires GAEN app providers to include a proprietary library with their app (the compiled .aar file you see in pretty much every GAEN app repository). Or in short terms: Google's implementation of GAEN is not open-source and every app using it is not free software<sup>1</sup>.

As @alohapersona wrote, microG provides a fully open-source implementation of the GAEN protocol for Android including drop-in replacement service and library. This allows to easily create GAEN compatible apps for Android that are actually free-software. Moreover, those app will also run on devices that don't have proprietary Google components on their operating system.

CCTG is a fork of CWA using microG instead of Google libraries. As such, it became free software and thus eligible to be included in F-Droid.

I surely can answer more questions about CCTG or microG. We can also chat or call if you think that helps :smile: 

<sub>1: The iOS implementation is also not open-source, but it does not require apps that want to use it to statically link a non-free library and thus such apps can be published as free software. Though, due to iOS being a locked operating system, free software for it doesn't matter as much anyway.</sub>

**Comment by dahoum** [comment]
Thanks! Looking forward to hear from him.

**Comment by dahoum** [comment]
We posted exactly at the same time :D Let me take this internally and come back to you! LFPH began w/ strong focus on GAEN w/ the plan to relax this over time, sadly Dan Kohn—the founder and director of LFPH unexpectedly and suddenly passed away and LFPH is currently re-organising. Will come back to you ASAP on this!

**Comment by mar-v-in** [comment]
Just to clarify this: microG is an alternative implementation of GAEN. It's fully compatible in the sense that apps/devices that use microG's GAEN implementation speak the same Bluetooth protocol and thus can fully interoperate with apps/devices using Apple's or Google's implementation of GAEN. Google and Apple create the protocol, but that doesn't mean others can't implement them. Huawei also created an alternative GAEN implementation for their Android devices. The finnish koronavilkku Android app is compatible with GAEN implementation of Google and Huawei.

**Comment by jennydove** [comment]
Hi all, sorry for the slow response but happy to jump in here. 

You're welcome to add this to the landscape and it does need a Crunchbase - the directions you found are exactly right, create a nonprofit organization on the site and so long as it has a headquarters location (City and country only) then you should be fine. If there's a Twitter account that would be helpful too - the way this tool was designed it pulls a lot of data from GitHub, and if your project isn't hosted on GitHub then it's going to look at your twitter feed to determine whether the project is "active" or not. Without a Twitter and GitHub both, the project will be auto-archived in a few months. (see https://github.com/lfph/lfph-landscape#non-updated-items) Or you can come back in 3 months to re-add and do that to keep it updated. 

Let me know if this helps answer your questions, and thank you so much for adding to the landscape!

**Comment by dahoum** [comment]
I'm happy to help w/ the Crunchbase if Jenny approves the card in general.

**Comment by jennydove** [comment]
Closing this due to inactivity. If you'd like to re-open it, feel free.

**Pull request closed without merging**
