### PR TITLE
Improve France part

### PR DESCRIPTION
**Pull request by LeoColomb**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Is your app/project/product currently shipping and/or have the source code available?
* [x] If an app, does your homepage include links to download the Android and/or iOS apps?
* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

---

* New app name
  Ref: https://www.economie.gouv.fr/tousanticovid
* Add source repository URL
  Ref: https://tousanticovid.stonly.com/kb/guide/fr/code-source-public-EUJJopdwEx/Steps/113599

### CODE REVIEW

**Comment by jennydove** [comment]
Leo, thank you so much for this update! At this moment the landscape repos only support GitHub pages. I hope we can add support for gitlab sites in the future. For the tests to pass, please remove the `additional_repos:` and try again.

**Comment by LeoColomb** [comment]
@jennydove That is sad! 😢 At least just linking repo link should be possible, I guess.
Anyway, commented out.

**Comment by jennydove** [comment]
I agree! If you'd like to work on those upstream changes, you're not alone. I just added a comment to the issue to try and get more attention on it. https://github.com/cncf/landscapeapp/issues/532

**Comment by jennydove** [comment]
One last thing - we need to update the image to have the title of the project match. I went ahead and created a new image 
- can you upload? 
- 
[france.svg.zip](https://github.com/lfph/lfph-landscape/files/6141853/france.svg.zip)

**Comment by jennydove** [comment]
Heard this back on my comment: 

> You can use other_repo_url instead of repo_url, it should not error out but it won't fetch any information regarding the repo either. This is for the main repo, not for additional_repos, but I could also add support for other_repo_url inside additional_repos.

Should we do this instead?

**Comment by LeoColomb** [comment]
Just did it. Not sure the right way though, loading fail on the test site...

**Comment by jennydove** [comment]
Ah yeah this is where the tool is rather particular. I think `other_repo_url` can't have nested URLs underneath it. So I've replaced it with just the one link and it appears to work. I'll add on the other ticket that being able to support multiple other repos in GitLab would be appreciated. Up to you whether to use the repo I linked or another one. 

Thank you for improving the landscape and feel free to merge whenever you're ready!

**Comment by LeoColomb** [comment]
All good, lgtm! 👍

**Comment by jennydove** [comment]
Great news! 

> @jennydove changed the code to accept gitlab repos (or any URL really) for additional_repos. I've also changed it so you can use repo_url for gitlab instead of other_repo_url, that's both for the main repo and additional repos. (https://github.com/cncf/landscapeapp/issues/532#issuecomment-809177041)

So if you'd like to add the other repos back it should now work.

**Pull request merged**
