### PR TITLE
Add Portugal (STAYAWAY COVID)

### PR DESCRIPTION
**Pull request by djcouto**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Is your app/project/product currently shipping and/or have the source code available?
* [x] If an app, does your homepage include links to download the Android and/or iOS apps?
* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by djcouto** [comment]
Hi,

For some reason, my SVG file is not being properly rendered as you can see [here](https://deploy-preview-29--lfph.netlify.app/logos/portugal-stayaway-covid.svg).

Do you any idea what is happening?

**Comment by dahoum** [comment]
I'm looking into it.

**Comment by dahoum** [comment]
What kind of flag is that? For Portugal I find this: https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg

**Comment by dahoum** [comment]
I took over your changes in a branch te-Portugal here and will fix/process them from there there.

**Comment by dahoum** [comment]
You might want to close this PR.
Also you should probably remove the lfph landscape fork from your repositories as else it will appear on the card of the app.

**Comment by djcouto** [comment]
Thank you for your help.
Closing this PR and the fork.

**Pull request closed without merging**
