### PR TITLE
Add corrected Ratio logo

### PR DESCRIPTION
**Pull request by jc00ke**
The previous version collapsed the `Public Benefit Corp` text spacing. This version was exported by our designer to address that issue.

### CODE REVIEW

**Comment by jc00ke** [comment]
If the new versions needs to be smaller to match the original, I'd love some help with that. I'm not adept in the graphic arts :wink:

**Comment by jc00ke** [comment]
image
Still busted, but I wonder if that's because the deploy script "optimizes" the file to be all on one line?

**Comment by jennydove** [comment]
Try running it through the autocrop tool and see if that fixes it? 

https://autocrop.cncf.io/

**Comment by jc00ke** [comment]
image
It does not :cry: 

I'll see if I can get a designer's help.

**Comment by jc00ke** [comment]
Reported as cncf/svg-autocrop#34

**Comment by jc00ke** [comment]
LGTM on the Netlify deploy preview!

**Comment by jmertic** [comment]
Already fixed by nightly build

**Pull request closed without merging**
