### PR TITLE
New Zealand Open Sources COVID Tracer App w/ Bluetooth+AGPL

### PR DESCRIPTION
**Pull request by hh**
This commit is in honor and memory of Dan Kohn:

 - founder of Linux Foundation Public Health
 - the storyteller and visionary of the landscape app
 - a deeply missed mentor who empowered so many

Thank you Dan for being a part of New Zealand`s Open Source Story.
I know you'd be proud to see this become reality.

🇳🇿

See: https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus/covid-19-resources-and-tools/nz-covid-tracer-app/open-source-release-nz-covid-tracer

### CODE REVIEW

**Comment by phindmarsh** [comment]
:shipit:

**Comment by hh** [comment]
Thanks. for the :shipit: @phindmarsh 
/lgtm

**Comment by dahoum** [comment]
The repositories have been added.
The repositories look good.
The landscape looks good.

**Comment by dahoum** [comment]
LGTM

**Pull request merged**
